### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by gabrielrfernandes** [jessieren/DeepVirFinder#11]
I used DeepVirFinder many times before, but suddenly it is running into an error. I removed the conda enviroment and installed again, but the error persists.
Here is the output:

`python dvf.py -i /home/gabrielfernandes/tools/DeepVirFinder/test/crAssphage.fa -o /home/gabrielfernandes/tools/DeepVirFinder/teste/ -c 10
1. Loading Models.
   model directory /home/gabrielfernandes/tools/DeepVirFinder/models
2020-07-31 12:57:39.613175: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-07-31 12:57:39.645270: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2297270000 Hz
2020-07-31 12:57:39.648272: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564fe738dd10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-31 12:57:39.648302: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-31 12:57:39.648400: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/site-packages/tensorflow/python/keras/utils/conv_utils.py:233: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.copy(kernel[slices])
WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
2. Encoding and Predicting Sequences.
   processing line 1
   processing line 1389
Traceback (most recent call last):
  File "dvf.py", line 211, in <module>
    pool = multiprocessing.Pool(core_num)
  File "/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/multiprocessing/pool.py", line 156, in __init__
    self._setup_queues()
  File "/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/multiprocessing/pool.py", line 249, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/multiprocessing/queues.py", line 315, in __init__
    self._rlock = ctx.Lock()
  File "/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/home/gabrielfernandes/miniconda2/envs/dvf/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied`

**Comment by jessieren** [comment]
Hi there,

Sorry for my late response. It is possible that the error was due to the version of Keras changes overtime. Could you please reinstall the packages following the exact versions of keras, theano, and python:

> conda create --name dvf python=3.6 numpy theano=1.0.3 keras=2.2.4 scikit-learn Biopython h5py
> source activate dvf

Thanks.
