### ISSUE TITLE
OSError: Unable to open file (unable to lock file)

### ISSUE THREAD

**Issue by snayfach** [jessieren/DeepVirFinder#19]
Running into an error with the code:

`DeepVirFinder> python3 dvf.py -i ./test/crAssphage.fa -o ./test/ -l 300`

> Using Theano backend.
> 1. Loading Models.
>    model directory /global/projectb/scratch/snayfach/projects/checkv-db/4_viral/DeepVirFinder/models
> Traceback (most recent call last):
>   File "dvf.py", line 131, in <module>
>     modDict[contigLengthk] = load_model(os.path.join(modDir, modName))
>   File "/global/homes/s/snayfach/.conda/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 417, in load_model
>     f = h5dict(filepath, 'r')
>   File "/global/homes/s/snayfach/.conda/envs/dvf/lib/python3.6/site-packages/keras/utils/io_utils.py", line 186, in __init__
>     self.data = h5py.File(path, mode=mode)
>   File "/global/homes/s/snayfach/.conda/envs/dvf/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
>     swmr=swmr)
>   File "/global/homes/s/snayfach/.conda/envs/dvf/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 85, in h5py.h5f.open
> OSError: Unable to open file (unable to lock file, errno = 524, error message = 'Unknown error 524')

Any ideas what could be wrong? Using the latest version from conda

**Comment by snayfach** [comment]
Solution: `export HDF5_USE_FILE_LOCKING=FALSE`
