### ISSUE TITLE
filelog not imported

### ISSUE THREAD

**Issue by askerdb** [jessieren/DeepVirFinder#22]
The code to show the help crashes with:

dvf.py: ERROR: missing required command-line argument
Traceback (most recent call last):
  File "dvf.py", line 33, in <module>
    filelog.write(prog_base + ": ERROR: missing required command-line argument")
NameError: name 'filelog' is not defined

The filelog is not instantiated anywhere I can see.

**Comment by jessieren** [comment]
Thanks for reporting that. Could you copy your command here for the purpose of debugging?

**Comment by askerdb** [comment]
It should work with any command that doesn't include the input argument

(dvf) -bash-4.2$ python dvf.py -o test
dvf.py: ERROR: missing required command-line argumentTraceback (most recent
call last):
  File "dvf.py", line 33, in <module>
    filelog.write(prog_base + ": ERROR: missing required command-line
argument")
NameError: name 'filelog' is not defined

**Comment by zhongshengbin269** [comment]
hi!
I also encountered this when running the code:
**line 33, in <module>
    filelog.write(prog_base + ": ERROR: missing required command-line
argument")
NameError: name 'filelog' is not defined**
How should excuse me solve?
