### ISSUE TITLE
Runtime Error during test-run

### ISSUE THREAD

**Issue by Jay1843** [jessieren/DeepVirFinder#28]
When tryying to run the test i always get this error.

(dvf) C:\Users\X\DeepVirFinder>python dvf.py -i ./test/crAssphage.fa -o ./test/ -l 300
Using Theano backend.
1. Loading Models.
   model directory C:\Users\X\DeepVirFinder\models
2. Encoding and Predicting Sequences.
   processing line 1
   processing line 1389
Using Theano backend.
1. Loading Models.
   model directory C:\Users\X\DeepVirFinder\models
2. Encoding and Predicting Sequences.
   processing line 1
   processing line 1389
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\X\.conda\envs\dvf\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\X\.conda\envs\dvf\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\X\.conda\envs\dvf\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\X\DeepVirFinder\dvf.py", line 211, in <module>
    pool = multiprocessing.Pool(core_num)
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\X\.conda\envs\dvf\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by zhongshengbin269** [comment]
Hi there,
May I ask you how to solve this problem?
I have the same problem as you.

**Comment by Jay1843** [comment]
I only used the program briefly, but I think a fresh linux installation fixed my problem.
