### ISSUE TITLE
problem when running dvf on HPC

### ISSUE THREAD

**Issue by leihuaxin** [jessieren/DeepVirFinder#43]
I used conda to install dvf following the githup steps. But when I submitted my script to HPC, there is a problem:
##
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Using Theano backend.
miniconda3/envs/dvf/lib/python3.6/site-packages/theano/configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
Traceback (most recent call last):
  File "tools/DeepVirFinder/dvf.py", line 132, in <module>
    modDict[contigLengthk] = load_model(os.path.join(modDir, modName))
  File "miniconda3/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "miniconda3/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 224, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
##
But when I run the same script on the local computer, no such problem. It's really strange. 
Anyone know how to address this problem? Thanks!

**Comment by nduan1** [comment]
@leihuaxin I got the same problem.

**Comment by dionisiosk** [comment]
@leihuaxin as mentioned in [this](https://github.com/jessieren/DeepVirFinder/issues/18) issue, try downgrading h5py to 2.10.0
